### ISSUE TITLE
Bug: Latest two forecasts contours are overlaid by each other

### ISSUE THREAD

**Issue by HF7weatherman** [orcestra-campaign/weather#110]
Since taking all latest five forecasts into account and not only the latest 5 12UTC forecasts, the latest two forecasts in the precipitation are always on top of each other, indicating they are the same.
Possible solutions would be to either remove the plotting of the second latest forecast at all or properly fix the code.

@dspraturi What's your opinion on this?

**Comment by dspraturi** [comment]
Maybe we can properly fix the code. But also, we don't even mention that there are two forecasts overlaid on top of one another when showing the weather briefing. So just keeping one forecast could also work. What do you think?

**Comment by HF7weatherman** [comment]
Seems to be a deeper problem. Also for the ICWV there is an overlay of the two latest forecasts.
I'll get into it, but cannot do so before Monday. So feel free to fix it earlier if you would like to. Nevertheless, this does not change anything with regard to our decision on precip, which we just discussed 👍🏻

**Comment by HF7weatherman** [comment]
Update: The observed behaviour only happens when we use a 12UTC forecast as the latest one, but not when using a 00UTC as the latest one.
