### ISSUE TITLE
Include Meteors position at the time of the briefing 

### ISSUE THREAD

**Issue by sortega87** [orcestra-campaign/weather#116]

**Comment by sortega87** [comment]
Hi @dspraturi, @HF7weatherman, @karstenpeters , @Lucalino. This issue is a request from Daniel. My thinking is that would have to coordinate first how to obtain the planned position on a daily basis. 

@hansmsc90 do you know how we can obtain the position?

**Comment by HF7weatherman** [comment]
FYI: @lkluft is implementing a way to download the Meteor's position from the PLANET system. We will include the Meteor's position in the weather briefings as soon as possible.

**Comment by lkluft** [comment]
We just release `v0.0.13` of the `orcestra` which includes a function the request the METEOR track from PLANET:
```py
from orcestra.meteor import get_meteor_track


meteor = get_meteor_track(deduplicate_latlon=True)
meteor
```
