### ISSUE TITLE
Include coordinates in the dust forecast plots

### ISSUE THREAD

**Issue by sortega87** [orcestra-campaign/weather#117]

**Comment by sortega87** [comment]
Hi @dspraturi, @HF7weatherman, @karstenpeters , @Lucalino. This issue is also a request from Meteor.

**Comment by HF7weatherman** [comment]
Hi @sortega87 and @hansmsc90! Including coordinates to the dust plots would be quite complicated, as the dust plots are cropped downloaded images from the [ECMWF charts](https://charts.ecmwf.int/products/aerosol-forecasts?base_time=202408190000&layer_name=composition_duaod550&projection=classical_west_tropic&valid_time=202408190300). Therefore, one first would somehow need to convert the png-files to matplotlib figures and then add the coordinates somehow. In principle, this would be possible, however, we wonder whether this comparatively huge investment is really necessary given that the geographic region shown is pretty obvious. In our opinion this would be a rather cosmetic addition...
Currently, we have a few other more urgent issues to fix, while this one is of much lower priority. Additionally, tomorrow is the off-day. Therefore, we won't work on this one before the weekend.

**Comment by sortega87** [comment]
Hi @HF7weatherman! Thanks! I took a look and it was not difficult as we were expecting, mostly as we have a similar functions for the NHC analysis developed by Lukas. I have made the changes and linked a pull request.

**Comment by HF7weatherman** [comment]
Hi @sortega87, thank you very much for the changes! :) I didn't expected it to be that easy and fast.
