### ISSUE TITLE
Bug in plotting ICWP plots

### ISSUE THREAD

**Issue by HF7weatherman** [orcestra-campaign/weather#15]
See file: https://github.com/orcestra-campaign/weather/blob/main/src/wblib/figures/internal/icwv.py

Currently, the function `iwv_itcz_edges()` plots only the second latest forecast, but not the latest. This is due to the fact that lines 37 & 38 select only the data for the previous five days, but not the current one. The forecast of the current day is not selected at all. I suggest to fix this problem by changing `range(1, 6)` to `range(0, 6)` in function `_get_dates_of_previous_five_days()` (line 66 of the file).
In that case it would also make sense to change the name of `_get_dates_of_previous_five_days()` to something like `_get_dates_of_previous_five_initializations()`.

@sortega87 Please doublecheck and confirm the bug, then I'll take care of fixing it.

**Comment by sortega87** [comment]
Hi Henning, 

Thanks for catching the bug! I agree on the changes as you suggest. My only comment is that the range should be range(0, 5) instead of range(0, 6).

**Comment by sortega87** [comment]
> Just a short tip for future discussions. On Github, you can use the permalink of any file and append `#L` to refer to specific lines, e.g.:
> 
> ```
> https://github.com/orcestra-campaign/weather/blob/2b74873a05e0abd6c8a5930f2221c292767b5caf/src/wblib/figures/internal/icwv.py#L37-L38
> ```
> 
> This will render the corresponding line(s) in place:
> 
> https://github.com/orcestra-campaign/weather/blob/2b74873a05e0abd6c8a5930f2221c292767b5caf/src/wblib/figures/internal/icwv.py#L37-L38

Thanks for the tip Lukas, it is quite useful :)

**Comment by sortega87** [comment]
This is being addressed in https://github.com/orcestra-campaign/weather/pull/27

**Comment by sortega87** [comment]
This was addressed with pull request https://github.com/orcestra-campaign/weather/pull/27
