### ISSUE TITLE
Probabilistic precipitation forecasts

### ISSUE THREAD

**Issue by HF7weatherman** [orcestra-campaign/weather#168]
As we now have the ensemble forecast for accumulated precipitation available, I created two different plots for probabilistic precipitation forecasts: a spaghetti plot of the 50mm/day precipitation rate threshold and a probability of reaching that threshold.

![precip_enfo_probability1](https://github.com/user-attachments/assets/5f4f380c-08f6-4dc5-890c-02aafd00cc0a)
![precip_enfo_spaghetti1](https://github.com/user-attachments/assets/cba0dd58-86c0-4a4e-8bc6-815e084d3ccc)

The data these plots show is the 3-hourly precipitation rate converted to the unit mm/day in the three hours before the valid time. The precipitation rate is derived from the accumulated precipitation (IFS variable `tp`). One could change this to the daily accumulated precipitation for each day. The motivation to show the 3-hourly precipitation rate instead of the accumulated daily precipitation is to give a more accurate estimate where deep convection is present at the valid time.

@karstenpeters @sortega87 @Lucalino @dspraturi: Any opinions on these plots? Which one do you prefer? Would you choose a different threshold than 50mm/day? My current thinking would be to include one of them to the briefing since they could form a valuable additional resource for flight planning, but don't discuss them in detail in the briefing as this would make the briefing too long.
@JuliaWindmiller1987 @bjorn-stevens: Any opinions on this?

@sortega87: In case we implement this, we should first address #163 to avoid that generating the briefing takes unacceptably long.

**Comment by dspraturi** [comment]
I would prefer the first probability plot between the two plots: It is easier to understand and would also take up less time during the briefing to explain.

**Comment by HF7weatherman** [comment]
Also Julia prefers the first plot. Thus, I will implement it tomorrow as part of the new section `Supporting figures`.
