### ISSUE TITLE
Maps of forecasted convergence

### ISSUE THREAD

**Issue by HF7weatherman** [orcestra-campaign/weather#169]
@JuliaWindmiller1987 expressed interest in maps of forecasted convergence. This should be easy in principle as long as we have regularly spaced lat-lon data. We can start thinking about this on Barbados 👍🏻

**Comment by dspraturi** [comment]
@HF7weatherman I also have codes that can compute convergence on healpix grids, so lat-lon data is not needed. Should I take a look at this issue and write the function?

**Comment by HF7weatherman** [comment]
Hi @dspraturi! It would be amazing if you could have a look and take responsibility of this issue. :)
