### ISSUE TITLE
Goes2Go plotting function can fail due to not finding the correct date in the sat tracks

### ISSUE THREAD

**Issue by sortega87** [orcestra-campaign/weather#190]
The following line can throw an error when the briefing time is not found in the satellite track. This can happen, for instance, when generating yesterday's goes figure when the flight track have been updated for the day.

https://github.com/orcestra-campaign/weather/blob/28f9ae12fcbed8a57eb70e9d3f8b9641921c8b3e/src/wblib/figures/external/goes_2_go.py#L111-L112

**Comment by HF7weatherman** [comment]
Just as a reminder: Here we should also remove the plotting of satellite tracks in the satellite images in general 😉
