### ISSUE TITLE
Add 5 latest forecasts of doldrum lines to weather briefing

### ISSUE THREAD

**Issue by HF7weatherman** [orcestra-campaign/weather#199]
This feature is requested by Julia.

**Comment by HF7weatherman** [comment]
Hi everyone! I've implemented the requested change as you can see in the plot below. In my opinion, we shouldn't implement this feature as the plot becomes too messy. In my opinion, the only useful way of adding more substance to the doldrums forecast would be to include an ensemble forecast of the 3m/s-doldrum line. However, I don't think this is worth the effort considering that the campaign is over in two weeks. @Lucalino @sortega87 What do you think?

36h leadtime:
![test_sfc_winds_36H](https://github.com/user-attachments/assets/7e94952c-9b5f-4386-918f-c123a3bdc82c)

108h leadtime:
![test_sfc_winds_108H](https://github.com/user-attachments/assets/8434f457-2ef7-4133-ba72-7d7dec5c8ef2)

Anyways, I'll keep these developments on a branch, so if someone wants them we have them still available.

**Comment by sortega87** [comment]
Thanks for implementing this Henning! I agree that they make the plots harder to read, so I would also think is better to make them on demand, as you suggest. I think they have useful information.

**Comment by sortega87** [comment]
Closing the issue as we will keep the figures in a development branch.
