### ISSUE TITLE
Random rendering since refactoring build process

### ISSUE THREAD

**Issue by HF7weatherman** [orcestra-campaign/weather#32]
Since the refactoring of the build process (#28), executing `quarto render --profile slides` causes quarto to render kind of random briefings, but definitely not always the latest briefing.
According to @sortega87 this is fixed by doing a `touch` on the briefing directory which should be rendered.
However, @sortega87 and me think this could be potentially dangerous as it could end up someone presenting the wrong briefing when forgetting to `touch` the latest briefing. Thus, we wondered whether it would make more sense to use a script again to render in order to make sure the correct date is used.

@lkluft What's you're opinion on this?

**Comment by lkluft** [comment]
The idea is that quarto will render every presentation that is **not yet build**. So, for example, if you do a fresh clone of the repo quarto will render **all** slides. If you now run quarto again, nothing should happen. Afterwards, only those slides that have been touched, changed or added should be build.

That is also the behaviour that I observe in the current main branch on my machine. If quarto behaves different for you, we can check on Monday why that is.

**Comment by HF7weatherman** [comment]
Hey @lkluft, could you please provide me the command to have a look on the rendered Quarto files? I forgot about it...

**Comment by lkluft** [comment]
If you have already rendered all files locally, you can simply open `public/index.html` in your web browser.

Alternatively, you can run `quarto preview --profile slides` to start the preview server for the slide shows.

**Comment by HF7weatherman** [comment]
Thanks for your quick answer. How can I open `public/index/html` in my web browser?

**Comment by lkluft** [comment]
You can either run `open public/index.html` from the terminal (MacOS) or open the following path directly in your browser `file:///absolute/path/to/public/index.html` in yo
