### ISSUE TITLE
Refactor plotting routines

### ISSUE THREAD

**Issue by HF7weatherman** [orcestra-campaign/weather#44]
At some point we should start refactoring the plotting routines, although this is not a task with high priority. To not loose track of what needs to be done, I started this issue. The following things came to my mind, please extend this list with your thoughts:

- Giving the location (i.e., Sal, Barbados, full Atlantic) as an argument to each plotting function to select plotting domain)
- Externalize some general tasks which occur in all plotting scripts, e.g. calculation of valid date
- ...

**Comment by sortega87** [comment]
Hi Henning,

Thanks for creating this issue. I think this is important to do to keep complexity from growing. 

To address this I think we should have a common interface to all figures. This means that we pass the same information to all functions, and each functions decides which information is useful for their purposes. The information that I believe is important to pass to each function is **current_time**, **briefing_time**,  **lead_time*, **location**,  and the **intake catalog object**, or an object that allows working with it for the purposes of the library.
